# # 本地开发环境配置
# server:
#   port: 8209
#   servlet:
#     context-path: /api
#   tomcat:
#     basedir: ./tomcat-temp

# spring:
#   datasource:
#     type: com.alibaba.druid.pool.DruidDataSource
#     driverClassName: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://localhost:3306/grape?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
#     username: root
#     password: root
#   # 禁用不需要的服务
#   autoconfigure:
#     exclude:
#       - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
#       - org.springframework.boot.autoconfigure.data.neo4j.Neo4jDataAutoConfiguration

# # 禁用Minio配置
# minio:
#   enabled: false

# # 简化日志配置
# logging:
#   level:
#     org:
#       springframework:
#         security: WARN
#     com:
#       grape:
#         grape:
#           mapper: INFO
#           service:
#             impl: INFO
